# Generated by Django 2.1.15 on 2021-01-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210113_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptednote',
            name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EncryptedNote',
        ),
    ]
