# Generated by Django 2.1.15 on 2021-01-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210114_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='password',
        ),
    ]
