# Generated by Django 2.1.15 on 2021-01-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_note_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='shared_to',
        ),
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
