# Generated by Django 2.1.15 on 2021-01-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210114_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='nonce',
        ),
    ]
